language: java

jdk:
  - openjdk11

services:
  - docker

env:
  global:
    - OPENSHIFT_REGISTRY="openshift-registry.adorsys.de"
    - OPENSHIFT_NAMESPACE_BANKING_GATEWAY_DEV="banking-gateway-dev"
    - OPENSHIFT_NAMESPACE_BANKING_GATEWAY_INTEG="banking-gateway-integ"

git:
  submodules: false

cache:
  directories:
    - .autoconf
    - $HOME/.m2

install:
  - mvn --settings .travis/settings.xml clean install -DskipTests -Dmaven.javadoc.skip=true -B -V -q

script:
  - /bin/bash .travis/build.sh

before_deploy:
  - echo $GPG_SECRET_KEY | base64 --decode | $GPG_EXECUTABLE --import || true
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust || true

deploy:
  -
    skip_cleanup: true
    provider: script
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
      # matches: vX.Y.Z, vX.Y.Z-A, vX.Y.Z-RCA, vX.Y.Z-A-B.C.D, vX.Y.Z-A-B.C.D-E, vX.Y.Z-RCA-B.C.D-E
      condition: "$TRAVIS_TAG =~ ^v([[:digit:]]+\\.)+[[:digit:]]+(-(RC)?[[:digit:]]+)?(-([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?)?$"
  -
    skip_cleanup: true
    provider: script
    script: /bin/bash .travis/deploy.sh
    on:
      branch: develop
 # Deploy to opehsift banking-gateway-dev
  - provider: script
    skip_cleanup: true
    script: env TAG=latest OPENSHIFT_NAMESPACE=$OPENSHIFT_NAMESPACE_BANKING_GATEWAY_DEV  OPENSHIFT_USER=$OPENSHIFT_BANKING_GATEWAY_DEV_USER OPENSHIFT_TOKEN=$OPENSHIFT_BANKING_GATEWAY_TOKEN /bin/bash -c '.travis/deploy_openshift_multibanking_service.sh && .travis/deploy_openshift_multibanking_app.sh'
    on:
      branch: develop
 # Deploy to opehsift banking-gateway-integ
  - provider: script
    skip_cleanup: true
    script: env TAG=latest OPENSHIFT_NAMESPACE=$OPENSHIFT_NAMESPACE_BANKING_GATEWAY_INTEG  OPENSHIFT_USER=$OPENSHIFT_BANKING_GATEWAY_INTEG_USER OPENSHIFT_TOKEN=$OPENSHIFT_BANKING_GATEWAY_INTEG_TOKEN /bin/bash .travis/deploy_openshift_multibanking_app.sh
    on:
      branch: develop


